### ISSUE TITLE
Problem concurrent execution of maven profiledep extension

### ISSUE THREAD

**Issue by reitzmichnicht** [sviperll/ozymandias#10]
Hi

With the upgrade of Intellij to versions of 2022.3 and higher there is a problem with this maven extension:
https://youtrack.jetbrains.com/issue/IDEA-316436
It looks like that it is not working for concurrent execution of maven.
Any chance to get this fixed?

Kind regards,
Michael

**Comment by sviperll** [comment]
Hi, Michael

I haven't touched this codebase for quite some time. I've released `0.24-beta2` version of the `maven-profiledep-extension`.
Can you probably try it and see if it fixes your problems:

```
<dependency>
  <groupId>com.github.sviperll</groupId>
  <artifactId>maven-profiledep-extension</artifactId>
  <version>0.24-beta2</version>
</dependency>
```

**Comment by zinnchen** [comment]
Version 0.24-beta2 fixes the problem. "Reload All Maven Projects" in IntelliJ 2023.1 is working fine now.
Thank you!

**Comment by reitzmichnicht** [comment]
Thank you for the quick fix, really great piece of software we are using for years now.
