### ISSUE TITLE
Profile activation based on properties does not seem to work

### ISSUE THREAD

**Issue by tonnymadsen** [sviperll/ozymandias#3]
I have a use-case where I want to combine maven-profiledep-extension with the "old" activation based on environment variables. But.. if I include maven-profiledep-extension in the mix, the other profiles does not seem to be activated.

I have lots of the following to setup the basic OSGi environment of the executing platform

```
    <profile>
        <id>win32-64-flags</id>
        <activation>
            <os>
                <family>windows</family>
                <arch>x86_86</arch>
            </os>
        </activation>
        <properties>
            <osgi.os>win32</osgi.os>
            <osgi.ws>win32</osgi.ws>
            <osgi.arch>x86_64</osgi.arch>
        </properties>
    </profile>
    <profile>
        <id>win32-32-flags</id>
        <activation>
            <os>
                <family>windows</family>
                <arch>x86</arch>
            </os>
        </activation>
        <properties>
            <osgi.os>win32</osgi.os>
            <osgi.ws>win32</osgi.ws>
            <osgi.arch>x86_64</osgi.arch>
        </properties>
    </profile>
```

But one of these are activated.

If I remove my extensions.xml, they are activated again as expected.

Any comments?

**Comment by sviperll** [comment]
I've thought this should work... Thank you for your report. I'll look into it. I'm short on time right now...

**Comment by sviperll** [comment]
Please, try version `0.21`. It should work there...
