### ISSUE TITLE
Support substitutions in <profile.depends>...</profile.depends>

### ISSUE THREAD

**Issue by tonnymadsen** [sviperll/ozymandias#4]
Simply support variable substitutions in the properties used to control maven-profiledep-extension, so it is possible to write something like:

```
<!-- Platform specific profiles -->
    <profile>
        <id>platform-flags</id>
        <properties>
            <profile.active>true</profile.active>
            <profile.depends>${os.family}-${os.arch}-flags,${os.family}-${os.version}-${os.arch}-flags</profile.depends>
        </properties>
    </profile>
    <profile>
        <id>windows-x86_86-flags</id>
        <properties>
            <profile.provides>osgi-platform</profile.provides>
            <osgi.os>win32</osgi.os>
            <osgi.ws>win32</osgi.ws>
            <osgi.arch>x86_64</osgi.arch>
        </properties>
    </profile>
```

**Comment by sviperll** [comment]
I'll look into it...

**Comment by sviperll** [comment]
It seems that it's impossible to get interpolated values in profile's properties. It seems that you can only use _some_ interpolation in `activation` element only.

See [maven-model-builder documentation](https://maven.apache.org/ref/3.2.5/maven-model-builder/)

> Notice that model interpolation happens _after_ profile activation, then profile activation doesn't benefit from every values: interpolation for file-based activation is limited to ${basedir} (which was introduced in Maven 3 and is not deprecated in this context), System properties and request properties.
