### ISSUE TITLE
Execution fails if target directory does not exist

### ISSUE THREAD

**Issue by akloeber** [sviperll/ozymandias#5]
If the parent directory of `outputPath` does not exist yet, the build fails. 

This prevents generating output into `${project.build.outputDirectory}` as directory `target/classes` may not exist yet which is always the case when running a clean build and having the mustache-maven-plugin bound to phase "validate". Like other plugins this plugin should create intermediate directories automatically if necessary.

Tested with mustache-maven-plugin@v0.22.

**Comment by sviperll** [comment]
Fixed in master
